env:
  global:
      - JAVA_OPTS="-Xmx512m -XX:MaxPermSize=256m"

language: groovy

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

after_success:
    - ./gradlew jacocoTestReport coveralls

sudo: false
