version: 2.1

build-job: &build-job
    steps:
        - checkout

        - restore_cache:
            keys:
                - gradle-repo-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                - gradle-repo-v1-

        - run: ./gradlew --build-cache build

        - run:
            command: |
                ./gradlew jacocoTestReport
                bash <(curl -s https://codecov.io/bash)

        - save_cache:
            paths:
                - ~/.gradle
            key: gradle-repo-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

        - store_test_results:
            path: ./build/test-results

jobs:
    build-jdk8:
        docker:
            - image: circleci/openjdk:8-jdk
        <<: *build-job
    build-jdk9:
        docker:
            - image: circleci/openjdk:9.0.1-jdk
        <<: *build-job
    build-jdk10:
        docker:
            - image: circleci/openjdk:10-jdk
        <<: *build-job
    build-jdk11:
        docker:
            - image: circleci/openjdk:11-jdk
        <<: *build-job

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build-jdk8
            - build-jdk9
            - build-jdk10
            - build-jdk11
